version: '3'

services:
  mysql_db:
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    build:
      context: ./..
      dockerfile: ./env/mysql-db/Dockerfile
    volumes:
      - "./mysql-db/init:/docker-entrypoint-initdb.d"
  node_app:
    container_name: node_app
    build:
      context: ./..
      dockerfile: ./env/node-app/Dockerfile
    volumes:
      - "./../src:/srv/app/src"
    depends_on:
      - mysql_db
    ports:
      - "8090:8090"